name: Tauri Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: ['rustfmt', 'clippy']

      # Step 3: Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        
      # Step 4: Install Tauri prerequisites based on the OS
      - name: Install Tauri dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt update
            sudo apt install -y libwebkit2gtk-4.0-dev libgtk-3-dev build-essential curl wget
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            choco install -y wix sharpdx
          fi

      # Step 5: Install dependencies and build the Tauri app
      - name: Install dependencies
        run: npm install

      - name: Build Tauri app
        run: npm run tauri build
      
      # Step 6: Upload build artifacts for download
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: src-tauri/target/release/bundle
